### ISSUE TITLE
Deforum fails to load

### ISSUE THREAD

**Issue by NUROISEA** [NUROISEA/anime-webui-colab#13]
```
Error loading script: deforum.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/stable-diffusion-webui/extensions/ext-deforum/scripts/deforum.py", line 17, in <module>
    import deforum_helpers.args as deforum_args
ModuleNotFoundError: No module named 'deforum_helpers'
```

**Comment by NUROISEA** [comment]
Kinda resolved, extension is not updated, experimental extensions installs deforum just fine.
