### ISSUE TITLE
NameError: name 'os' is not defined on MixPro Model

### ISSUE THREAD

**Issue by DigKingy** [NUROISEA/anime-webui-colab#23]
```bash
👍 Utility script imported.
🩹 Applying Colab memory fix...
env: LD_PRELOAD=libtcmalloc.so
🔼 Selected the latest version of the web UI.
🌟 Installing stable-diffusion-webui...
🔼 Installing the latest versions of the extensions.
📦 Installing 12 extensions...
  └ aspect-ratio-preset
  └ batchlinks
  └ cutoff
  └ dynamic-thresholding
  └ images-browser
  └ latent-couple-two-shot
  └ session-organizer
  └ state
  └ tagcomplete
  └ tiled-multidiffusion-upscaler
  └ tokenizer
  └ tunnels
🔧 Fetching configs...
💉 Fetching embeddings...
🩹 Applying web UI Colab patches...
📦 Installing aria2...
⏬ Downloading MIX-Pro-V4.safetensors to /content/stable-diffusion-webui/models/Stable-diffusion...
⏬ Downloading kl-f8-anime2.ckpt to /content/stable-diffusion-webui/models/VAE...
/content/stable-diffusion-webui
Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
Version: v1.3.0
Commit hash: 20ae71faa8ef035c31aa3a410b707d792c8203a3
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into /content/stable-diffusion-webui/repositories/taming-transformers...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements
Installing pycloudflared



Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 40, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 30, in main
    os.system(f"""sed -i -e "s/dict()))$/dict())).cuda()/gm" /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/util.py""")
NameError: name 'os' is not defined
```

**Comment by NUROISEA** [comment]
Ah, that patch is broken on the latest (and latest-dev most likely) version of the web UI.

For now, you have to use the stable version of the web UI or remove this code in the notebook if you wish to use the latest version:
![image](https://github.com/NUROISEA/anime-webui-colab/assets/120075289/5139c95f-60ac-4ee7-8494-d20035600f97)

It seems like the `launch.py` has changed and the main code has been moved to `modules/launch_utils.py` and that code snippet relies on a specific line, which is now gone lol

I'll find a janky workaround for this, thanks for reporting

**Comment by NUROISEA** [comment]
Well, I "fixed" this. Let me know if there are any more problems

**Comment by DigKingy** [comment]
Alright, thanks a bunch!
