### ISSUE TITLE
control net v1.1 is not working

### ISSUE THREAD

**Issue by morethancoder** [NUROISEA/anime-webui-colab#26]
```*** Error running process: /content/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/stable-diffusion-webui/modules/scripts.py", line 474, in process
        script.process(p, *script_args)
      File "/content/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py", line 736, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "/content/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py", line 299, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "/content/stable-diffusion-webui/extensions/controlnet/scripts/controlnet.py", line 365, in build_control_model
        assert os.path.exists(override_config), f'Error: The model config {override_config} is missing. ControlNet 1.1 must have configs.'
    AssertionError: Error: The model config /content/stable-diffusion-webui/extensions/controlnet/models/control_v11u_sd15_tile.yaml is missing. ControlNet 1.1 must have configs.

---
```

### i saw on other git repositories that is an issue with config files naming but how can i change the config files ?

**Comment by NUROISEA** [comment]
Ah, yeah I forgot to include the `.yaml` files, will be fixed shortly. Apologies, since I don't generate that often I glossed over this.

**Comment by NUROISEA** [comment]
Hi, @morethancoder can you try to see if my latest commit resolves this?

**Comment by NUROISEA** [comment]
Actually, I tested it myself. Works as expected.
