### ISSUE TITLE
(one of) ControlNet Extensions causing the webui to be not functional

### ISSUE THREAD

**Issue by Archinect** [NUROISEA/anime-webui-colab#28]
```
⏬ Downloading anything-v4.5-pruned.safetensors to /content/stable-diffusion-webui/models/Stable-diffusion...
👍 anything-v4.0.vae.pt already downloaded.
⌛ This might take a while! Grab a 🍿 or something xD

📢 These models are FP16, btw. ;)

🤙 Downloading 8 ControlNet v1.0 files/models...
👍 control_canny.safetensors already downloaded.
👍 control_depth.safetensors already downloaded.
👍 control_hed.safetensors already downloaded.
👍 control_mlsd.safetensors already downloaded.
👍 control_normal.safetensors already downloaded.
👍 control_openpose.safetensors already downloaded.
👍 control_scribble.safetensors already downloaded.
👍 control_seg.safetensors already downloaded.
/content/stable-diffusion-webui
fatal: No names found, cannot describe anything.
Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Version: ## 1.4.0
Commit hash: 394ffa7b0a7fff3ec484bcd084e673a8b301ccc8
Installing requirements





Launching Web UI with arguments: --opt-sdp-attention --lowram --no-hashing --enable-insecure-extension-access --no-half-vae --disable-safe-unpickle --gradio-queue --ckpt /content/stable-diffusion-webui/models/Stable-diffusion/anything-v4.5-pruned.safetensors --vae-path /content/stable-diffusion-webui/models/VAE/anything-v4.0.vae.pt --share
No module 'xformers'. Proceeding without it.
2023-07-18 02:07:20,179 - ControlNet - INFO - ControlNet v1.1.232
ControlNet preprocessor location: /content/stable-diffusion-webui/extensions/controlnet/annotator/downloads
2023-07-18 02:07:20,343 - ControlNet - INFO - ControlNet v1.1.232
Image Browser: ImageReward is not installed, cannot be used.
Loading weights [None] from /content/stable-diffusion-webui/models/Stable-diffusion/anything-v4.5-pruned.safetensors
Running on local URL:  http://127.0.0.1:7860/
preload_extensions_git_metadata for 23 extensions took 0.93s
Running on public URL: https://afccdf8f9763638b98.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
Startup time: 19.9s (import torch: 8.3s, import gradio: 0.9s, import ldm: 0.5s, other imports: 1.5s, setup codeformer: 0.1s, load scripts: 2.1s, create ui: 2.7s, gradio launch: 3.7s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 271, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights from commandline argument: /content/stable-diffusion-webui/models/VAE/anything-v4.0.vae.pt
Applying attention optimization: sdp... done.
Textual inversion embeddings loaded(7): bad-artist, bad-artist-anime, bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative, EasyNegativeV2
Model loaded in 21.6s (load weights from disk: 13.9s, create model: 3.2s, load VAE: 4.1s, calculate empty prompt: 0.2s).
```

**Comment by NUROISEA** [comment]
To clarify, you selected `stable` as the webui version and `latest` for the extensions version?
