### ISSUE TITLE
Cannot launch web

### ISSUE THREAD

**Issue by Ayaya70** [NUROISEA/anime-webui-colab#53]
Here we go again
Got this after trying PYOM today on gradio using latest. 

> Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Launching Web UI with arguments: --opt-sdp-attention --lowram --no-hashing --enable-insecure-extension-access --no-half-vae --disable-safe-unpickle --gradio-queue --ckpt /content/models/ilovemymom_v30.safetensors --ckpt-dir /content/models --vae-dir /content/VAE --share
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 465, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/stable-diffusion-webui/modules/initialize.py", line 17, in imports
    import pytorch_lightning  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 28, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py", line 47, in <module>
    from pytorch_lightning.loggers import Logger
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/__init__.py", line 22, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py", line 36, in <module>
    import wandb
  File "/usr/local/lib/python3.10/dist-packages/wandb/__init__.py", line 21, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/__init__.py", line 28, in <module>
    from .wandb_init import _attach, init
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 39, in <module>
    from . import wandb_login, wandb_setup
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 19, in <module>
    from .wandb_settings import Settings
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_settings.py", line 25, in <module>
    from pydantic import (
ImportError: cannot import name 'computed_field' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)

**Comment by ErickFRL** [comment]
I have the same error

**Comment by NUROISEA** [comment]
Create a new cell and paste the following:

```
!pip uninstall wandb -y
!pip install wandb==0.15.12
```

There's a similar issue [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/16732) at AUTOMATIC1111/stable-diffusion-webui

Will push a fix so you don't have to.

**Comment by NUROISEA** [comment]
Pushed a fix, let me know if other stuff breaks lol

**Comment by Ayaya70** [comment]
Thank you the GOAT...
